### ISSUE TITLE
Let user specify opencc library path

### ISSUE THREAD

**Issue by x-ji** [gucong/emacs-chinese-conv#2]
If opencc is installed via `homebrew`, its library path will be at `/usr/local/Cellar/opencc/1.0.2/share/opencc` instead of `/usr/share/opencc`

**Comment by gucong** [comment]
It should be easy to modify the lines 54-76 to match new opencc configuration and calling conventions. It is also easy to add a customization variable for lib path.  I will look into this when I have time.  Patch is welcome.

**Comment by gucong** [comment]
fixed in d6d8c92
